name: "Lab CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Node dependencies
        run: npm ci
      - name: Run server
        run: npm run start &
      - name: Wait for server to start
        run: sleep 5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      # Первый запуск тестов для генерации скриншотов
      - name: Run tests to generate snapshots
        run: pytest || true

      # Сохранение сгенерированных скриншотов как артефактов
      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        with:
          name: snapshots
          path: testing/screenshot/snapshots/test_local_screenshots

      # Загрузить сохраненные скриншоты
      - name: Download snapshots
        uses: actions/download-artifact@v3
        with:
          name: snapshots
          path: testing/screenshot/snapshots/test_local_screenshots

      # Второй запуск тестов для проверки скриншотов
      - name: Run tests to verify snapshots
        run: pytest